name: SBM — Data Fetch & Preflight

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */6 * * *"   # every 6 hours

concurrency:
  group: sbm-data-preflight
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  fetch-and-preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
          # audit requirements (includes soccerdata from GitHub)
          if [ -f "audit/requirements.txt" ]; then pip install -r audit/requirements.txt; fi
          mkdir -p data reports

      - name: Fetch SPI (robust)
        run: python connectors/spi_fetch.py

      - name: Fetch FBref team stats
        run: python connectors/fbref_fetch.py

      - name: Fetch Odds + Fixtures (multi-provider, resilient)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}             # The Odds API
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}     # api-football.com key (not RapidAPI)
          # Optional: restrict leagues by provider IDs (comma-separated, see file for defaults)
          API_FOOTBALL_LEAGUE_IDS: ${{ vars.API_FOOTBALL_LEAGUE_IDS }}
        run: python connectors/multi_odds_fetch.py

      - name: Append source alerts to AUTO_BRIEFING
        run: python scripts/alerts_autobriefing_append.py

      - name: Upload data & reports
        uses: actions/upload-artifact@v4
        with:
          name: sbm-preflight-artifacts
          path: |
            data/*.csv
            reports/*.md
            reports/*.csv
            reports/*.json