name: SBM — Data Fetch & Preflight

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */6 * * *"

concurrency:
  group: sbm-data-preflight
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  fetch-and-preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
          if [ -f "audit/requirements.txt" ]; then pip install -r audit/requirements.txt; fi
          mkdir -p data reports

      - name: Fetch SPI (robust)
        run: python connectors/spi_fetch.py

      - name: Fetch FBref team stats (multi-slice)
        run: python connectors/fbref_fetch.py

      - name: Fetch Odds + Fixtures (two-key + normalized markets)
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
          THE_ODDS_API_KEY_BACKUP: ${{ secrets.THE_ODDS_API_KEY_BACKUP }}
        run: python connectors/multi_odds_fetch.py

      - name: Fetch Lineups (API-FOOTBALL)
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: python connectors/lineups_fetch.py

      - name: Alias audit (unmapped names)
        run: python scripts/alias_audit.py

      - name: Enrich upcoming fixtures (features for modeling)
        run: python scripts/enrich_features.py

      - name: Append source alerts to AUTO_BRIEFING.md
        run: |
          mkdir -p reports
          if [ ! -f reports/AUTO_BRIEFING.md ]; then echo "# AUTO BRIEFING" > reports/AUTO_BRIEFING.md; fi
          python scripts/alerts_autobriefing_append.py
          echo "" >> reports/AUTO_BRIEFING.md
          echo "## Odds Key Usage (from ODDS_ALERTS.md)" >> reports/AUTO_BRIEFING.md
          if [ -f reports/ODDS_ALERTS.md ]; then
            echo "" >> reports/AUTO_BRIEFING.md
            tail -n +1 reports/ODDS_ALERTS.md >> reports/AUTO_BRIEFING.md
          else
            echo "- No ODDS_ALERTS.md found this run." >> reports/AUTO_BRIEFING.md
          fi

      - name: Upload data & reports
        uses: actions/upload-artifact@v4
        with:
          name: sbm-preflight-artifacts
          path: |
            data/*.csv
            reports/*.md
            reports/*.csv
            reports/*.json