name: Soccer Betting Machine

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"  # daily at 09:00 UTC
  pull_request:
    branches: [ main ]

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: UTC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install joblib

      - name: Set PYTHONPATH (enable util_* imports)
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/scripts" >> $GITHUB_ENV

      - name: Prepare run directory
        id: datestamp
        run: |
          export RUN_DATE=$(date -u +%F)
          echo "RUN_DATE=$RUN_DATE" >> $GITHUB_ENV
          mkdir -p runs/$RUN_DATE
          mkdir -p data

      - name: Probe APIs (FBR / Odds API)
        env:
          FBR_API_KEY: ${{ secrets.FBR_API_KEY }}
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/test_endpoints.py

      - name: Fetch Football-Data (historical)
        run: python scripts/fetch_football_data.py

      - name: Fetch Odds (Odds API only; multi-sport sweep)
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/fetch_the_odds_api.py

      - name: Fetch via soccerdata (FBref + 538)
        run: python scripts/fetch_soccerdata.py

      - name: Fetch Understat xG (Big-5)
        run: python scripts/fetch_understat_xg.py

      - name: Fetch StatsBomb xG (open data)
        run: python scripts/fetch_statsbomb_xg.py

      - name: Scrape OddsPortal (optional secondary odds)
        run: python scripts/scrape_oddsportal.py || true

      - name: Normalize team names across sources
        run: python scripts/normalize_all_team_names.py

      - name: Merge FBref xG fallback into hybrid
        run: python scripts/merge_sd_fbref_into_xg.py

      - name: Merge Understat xG into hybrid (fill missing only)
        run: python scripts/merge_understat_into_xg.py

      - name: Merge StatsBomb xG into hybrid (fill missing only)
        run: python scripts/merge_statsbomb_into_xg.py

      - name: Build teams master (seed priors)
        run: python scripts/00_build_teams_master.py

      - name: Ensure minimal data files exist
        run: python scripts/ensure_min_files.py

      - name: Generate matchday injuries/lineups templates (next 7 days)
        run: python scripts/generate_matchday_templates.py

      - name: Build Upcoming 7-day window (enriched)
        run: python scripts/build_upcoming_window.py

      - name: Enrich fixtures (01 step)
        run: python scripts/01_enrich_fixtures.py

      - name: Enrich features (merge injuries/refs/stadium + SB team features)
        run: python scripts/enrich_features.py

      # NEW: engineer extra variables into UPCOMING_7D_enriched.csv
      - name: Engineer extra variables
        run: python scripts/engineer_extra_variables.py

      - name: Build HIST & UPCOMING
        run: python scripts/build_hist_and_upcoming.py

      - name: Sanity check inputs
        run: |
          test -f data/HIST_matches.csv || (echo "ERROR: data/HIST_matches.csv missing" && exit 1)
          test -f data/UPCOMING_7D_enriched.csv || (echo "ERROR: data/UPCOMING_7D_enriched.csv missing" && exit 1)

      - name: Emit quality report (03 step)
        run: python scripts/03_emit_quality_report.py

      - name: Check inventory (04 step)
        run: python scripts/04_check_inventory.py

      - name: Data inventory report (compat)
        run: python scripts/data_inventory_report.py

      - name: Data quality diagnostics (compat)
        run: python scripts/data_quality_diagnostics.py

      - name: Verify xG end-to-end
        run: python scripts/verify_xg_end_to_end.py

      - name: Odds coverage diagnostics
        run: python scripts/odds_coverage_diagnostics.py

      - name: Build league xG table
        run: python scripts/derive_league_table_metrics.py

      - name: Build rolling form features
        run: python scripts/build_rolling_features.py

      - name: Train feature model (1X2)
        run: python scripts/train_feature_model.py

      - name: Predict feature-model probabilities (upcoming)
        run: python scripts/predict_feature_model.py

      - name: Blend and calibrate (02 step)
        run: python scripts/02_blend_and_calibrate.py

      - name: Per-league blend weights table
        run: python scripts/per_league_blend_weights.py

      - name: Generate 7-day predictions (1X2 with calibrated blend + odds)
        run: python scripts/model_predict.py

      - name: Goals model (μ_home, μ_away)
        run: python scripts/goals_model.py

      - name: Totals pricing (main line 2.5)
        run: python scripts/totals_pricing.py

      - name: Train BTTS model (per-league)
        run: python scripts/train_btts_model.py

      - name: Predict BTTS (blend + isotonic per-league)
        run: python scripts/predict_btts_model.py

      - name: Consistency checks (1X2 ↔ Totals ↔ BTTS ↔ Spread)
        run: python scripts/consistency_checks.py

      - name: Kelly sizing & exposure caps
        run: python scripts/kelly_and_caps.py

      - name: Execution feasibility (liquidity/coverage)
        run: python scripts/execution_feasibility.py

      - name: Backtest evaluate
        run: python scripts/backtest_evaluate.py

      - name: Calibration report (bins + summary)
        run: python scripts/calibration_report.py

      - name: Calibration by league
        run: python scripts/calibration_by_league.py

      - name: Feature importance (explainability)
        run: python scripts/feature_importance.py

      - name: ROI by slice (weekly)
        run: python scripts/roi_by_slice.py

      - name: Coverage trends
        run: python scripts/coverage_trends.py

      - name: Feature drift (weekly)
        run: python scripts/feature_drift.py

      - name: Line move log (AM vs T-60)
        run: python scripts/line_move_log.py

      - name: Stacking log (BTTS meta-weights placeholder)
        run: python scripts/stacking_log.py

      - name: Council Briefing (expanded)
        run: python scripts/council_briefing.py

      - name: Ensure anti-model veto file
        run: |
          test -f runs/${{ env.RUN_DATE }}/ANTI_MODEL_VETOES.csv || echo "slice,reason" > runs/${{ env.RUN_DATE }}/ANTI_MODEL_VETOES.csv

      - name: Sanity (re)write blend weights + show paths
        run: |
          python scripts/per_league_blend_weights.py
          ls -l data/PER_LEAGUE_BLEND_WEIGHTS.csv || true
          ls -l runs/${{ env.RUN_DATE }}/PER_LEAGUE_BLEND_WEIGHTS.csv || true

      # NEW: model accuracy reports (after predictions/backtests)
      - name: Model accuracy report
        run: python scripts/model_accuracy_report.py

      - name: Schema check (headers & presence)
        run: python scripts/schema_check.py

      - name: Sync legacy outputs to RUN dir
        run: python scripts/sync_to_run_dir.py

      - name: Export sbm-7d-bundle (new consolidated zip)
        run: python scripts/export_artifacts.py

      - name: Upload legacy artifact set (compatibility)
        uses: actions/upload-artifact@v4
        with:
          name: sbm-legacy-artifacts
          path: |
            data/HIST_matches.csv
            data/UPCOMING_fixtures.csv
            data/UPCOMING_7D_enriched.csv
            data/PREDICTIONS_7D.csv
            data/DATA_INVENTORY_REPORT.csv
            data/DATA_QUALITY_REPORT.csv
            data/VERIFY_XG_REPORT.csv
            data/ODDS_COVERAGE_REPORT.csv
            data/LEAGUE_XG_TABLE.csv
            data/team_form_features.csv
            data/model_blend.json
            data/calibrator.pkl
            data/BACKTEST_SUMMARY.csv
            data/BACKTEST_BY_WEEK.csv
            data/CALIBRATION_TABLE.csv
            data/CALIBRATION_SUMMARY.csv
            data/ACTIONABILITY_REPORT.csv
            data/COUNCIL_BRIEFING.md
            data/feature_model.pkl
            data/feature_model_features.json
            data/feature_proba_upcoming.csv
            data/xg_metrics_current.csv
            data/xg_metrics_last.csv
            data/xg_metrics_hybrid.csv
            data/xg_understat.csv
            data/xg_statsbomb.csv
            data/team_statsbomb_features.csv
            data/sd_fbref_team_stats.csv
            data/sd_538_spi.csv
            data/teams_master.csv
            data/api_probe_report.json

      - name: Upload new zipped bundle
        uses: actions/upload-artifact@v4
        with:
          name: sbm-7d-bundle
          path: runs/${{ env.RUN_DATE }}/sbm-7d-bundle.zip