name: Soccer Betting Machine

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Probe APIs (FBR / Odds API)
        env:
          FBR_API_KEY: ${{ secrets.FBR_API_KEY }}
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/test_endpoints.py

      # --- your existing data fetch steps (keep them) ---
      - name: Fetch Football-Data (historical)
        run: python scripts/fetch_football_data.py

      - name: Consolidate odds (optional; builds data/manual_odds.csv)
        run: python scripts/consolidate_odds.py

      - name: Fetch Odds (API or manual override)
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/fetch_the_odds_api.py

      - name: Fetch FBR team xG (hybrid)
        env:
          FBR_API_KEY: ${{ secrets.FBR_API_KEY }}
        run: python scripts/fetch_fbr_team_xg.py

      - name: Fetch via soccerdata (FBref + 538)
        run: python scripts/fetch_soccerdata.py

      - name: Merge FBref xG fallback into hybrid
        run: python scripts/merge_sd_fbref_into_xg.py

      - name: Fetch Understat xG (Big-5)
        run: python scripts/fetch_understat_xg.py

      - name: Merge Understat xG into hybrid (fill missing only)
        run: python scripts/merge_understat_into_xg.py

      - name: Fetch StatsBomb xG (open data)
        run: python scripts/fetch_statsbomb_xg.py

      - name: Merge StatsBomb xG into hybrid (fill missing only)
        run: python scripts/merge_statsbomb_into_xg.py
      # --------------------------------------------------

      - name: Bootstrap team priors (optional)
        run: python scripts/bootstrap_team_priors.py

      - name: Ensure minimal data files exist
        run: python scripts/ensure_min_files.py

      - name: Generate matchday templates (next 7 days)
        run: python scripts/generate_matchday_templates.py

      - name: Build Upcoming 7-day window (enriched)
        run: python scripts/build_upcoming_window.py

      - name: Enrich features (normalize + merge xG/injuries/lineups/refs/stadium + SB team features)
        run: python scripts/enrich_features.py

      - name: Build HIST & UPCOMING
        run: python scripts/build_hist_and_upcoming.py

      - name: Data inventory report (what we have)
        run: python scripts/data_inventory_report.py

      - name: Data quality diagnostics (coverage)
        run: python scripts/data_quality_diagnostics.py

      - name: Build league xG table
        run: python scripts/derive_league_table_metrics.py

      # --- NEW ML STEPS ---
      - name: Build rolling form features
        run: python scripts/build_rolling_features.py

      - name: Train calibrated blend
        run: python scripts/train_calibrated_blend.py
      # ---------------------

      - name: Generate 7-day predictions (optional)
        run: python scripts/model_predict.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbm-7d-bundle
          path: |
            data/HIST_matches.csv
            data/UPCOMING_fixtures.csv
            data/UPCOMING_7D_enriched.csv
            data/PREDICTIONS_7D.csv
            data/DATA_INVENTORY_REPORT.csv
            data/DATA_QUALITY_REPORT.csv
            data/LEAGUE_XG_TABLE.csv
            data/team_form_features.csv
            data/model_blend.json
            data/calibrator.pkl
            data/xg_metrics_current.csv
            data/xg_metrics_last.csv
            data/xg_metrics_hybrid.csv
            data/xg_understat.csv
            data/xg_statsbomb.csv
            data/team_statsbomb_features.csv
            data/sd_fbref_team_stats.csv
            data/sd_538_spi.csv
            data/teams_master.csv
            data/api_probe_report.json
            data/manual_odds.csv