name: Soccer Betting Machine

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/scripts" >> $GITHUB_ENV

      - name: Probe APIs (FBR / Odds API)
        env:
          FBR_API_KEY: ${{ secrets.FBR_API_KEY }}
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/test_endpoints.py

      # Historical baseline
      - name: Fetch Football-Data (historical)
        run: python scripts/fetch_football_data.py

      # Odds strictly from API now (no manual override)
      - name: Fetch Odds (Odds API only)
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/fetch_the_odds_api.py

      # xG sources
      - name: Fetch via soccerdata (FBref + 538)
        run: python scripts/fetch_soccerdata.py

      - name: Fetch Understat xG (Big-5)
        run: python scripts/fetch_understat_xg.py

      - name: Fetch StatsBomb xG (open data)
        run: python scripts/fetch_statsbomb_xg.py

      # Normalize names using both maps
      - name: Normalize team names across sources
        run: python scripts/normalize_all_team_names.py

      # Merge xG into hybrid (fills only where missing)
      - name: Merge FBref xG fallback into hybrid
        run: python scripts/merge_sd_fbref_into_xg.py

      - name: Merge Understat xG into hybrid (fill missing only)
        run: python scripts/merge_understat_into_xg.py

      - name: Merge StatsBomb xG into hybrid (fill missing only)
        run: python scripts/merge_statsbomb_into_xg.py

      # Priors
      - name: Build teams master
        run: python 00_build_teams_master.py

      - name: Ensure minimal data files exist
        run: python scripts/ensure_min_files.py

      - name: Generate matchday injuries/lineups templates (next 7 days)
        run: python scripts/generate_matchday_templates.py

      # 7-day window (API fixtures fallback baked in)
      - name: Build Upcoming 7-day window (enriched)
        run: python scripts/build_upcoming_window.py

      # Enrichment
      - name: Enrich fixtures (01 step)
        run: python 01_enrich_fixtures.py

      - name: Enrich features (normalize + merge injuries/refs/stadium + SB extras)
        run: python scripts/enrich_features.py

      # Final schema
      - name: Build HIST & UPCOMING
        run: python scripts/build_hist_and_upcoming.py

      # Reports
      - name: Emit quality report (03 step)
        run: python 03_emit_quality_report.py

      - name: Check inventory (04 step)
        run: python 04_check_inventory.py

      - name: Data inventory report (compat)
        run: python scripts/data_inventory_report.py

      - name: Data quality diagnostics (compat)
        run: python scripts/data_quality_diagnostics.py

      - name: Build league xG table
        run: python scripts/derive_league_table_metrics.py

      # ML
      - name: Build rolling form features
        run: python scripts/build_rolling_features.py

      - name: Blend and calibrate (02 step)
        run: python 02_blend_and_calibrate.py

      - name: Generate 7-day predictions (no-manual-odds mode)
        run: python scripts/model_predict.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbm-7d-bundle
          path: |
            data/HIST_matches.csv
            data/UPCOMING_fixtures.csv
            data/UPCOMING_7D_enriched.csv
            data/PREDICTIONS_7D.csv
            data/DATA_INVENTORY_REPORT.csv
            data/DATA_QUALITY_REPORT.csv
            data/LEAGUE_XG_TABLE.csv
            data/team_form_features.csv
            data/model_blend.json
            data/calibrator.pkl
            data/xg_metrics_current.csv
            data/xg_metrics_last.csv
            data/xg_metrics_hybrid.csv
            data/xg_understat.csv
            data/xg_statsbomb.csv
            data/team_statsbomb_features.csv
            data/sd_fbref_team_stats.csv
            data/sd_538_spi.csv
            data/teams_master.csv
            data/api_probe_report.json